version: '1.0'

services:
  backend:
    image: node:18-alpine
    container_name: loyiha
    volumes:
      - ./:/app
    env_file:
      - backend/.env
    working_dir: /app
    command: sh -c "cd backend && npm i -f && npm run start:dev"
    ports:
      - 3000:3000
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
