services:
  server:
    image: node:22-alpine
    container_name: online-shop-backend
    volumes:
      - .:/project
    env_file:
      - .env
    working_dir: /project
    command: sh -c "npm install && npm run start"
    ports:
      - "${PORT:-3000}:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: for-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres:
